name: runTestsOnGithub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: runTestsOnGithub
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true